### ISSUE TITLE
VFB?

### ISSUE THREAD

**Issue by ctrlcctrlv** [hayk/anahit#1]
The README claims the font is in OpenType format, but it's actually in "VFB" format, a format I don't recognize. Not SFD, or GlyphsApp, or UFO. Any idea?

**Comment by khaledhosny** [comment]
[`vfb2ufo`](https://store.fontlab.com/index.php?option=com_mijoshop&route=product/category&path=34_51&Itemid=448)

**Comment by ctrlcctrlv** [comment]
Ah ha. It's FontLab's proprietary format. Thanks! And thanks for that tool, appreciated.
